version: "3"

services:
  api:
    build:
      dockerfile: ./api.Dockerfile
    ports:
      - '8083:8083'
    networks:
      - app
  prometheus:
    image: prom/prometheus:main-distroless
    ports:
      - '9090:9090'
    volumes:
      - './config/prometheus.yml:/etc/prometheus/prometheus.yml'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - api
    networks:
      - app

networks:
  app:
